build_from:
  amd64: ghcr.io/home-assistant/base-python:latest
  aarch64: ghcr.io/home-assistant/base-python:latest
  armv7: ghcr.io/home-assistant/base-python:latest
  armhf: ghcr.io/home-assistant/base-python:latest
  i386: ghcr.io/home-assistant/base-python:latest
